// Frontend/hacker-news-react/src/components/NewStories.tsx
import React, { useState, useEffect } from "react";
import { getNewStories } from "../services/HackerNewsService";
import "./NewStories.css"; // Import the CSS file

interface Story {
  url: string | undefined;
  title: string;
}

const NewStories: React.FC = () => {
  const [stories, setStories] = useState<Story[]>([]);
  const [page, setPage] = useState(1);
  const [limit] = useState(20);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchNewStories = async () => {
      try {
        const data = await getNewStories(page, limit, setLoading);
        setStories(data);
      } catch (error: unknown) {
        if (error instanceof Error) {
          console.error(error.message);
        } else {
          console.error("An unexpected error occurred:", error);
        }
      }
    };

    fetchNewStories();
  }, [page, limit]);

  const nextPage = () => setPage(page + 1);
  const prevPage = () => page > 1 && setPage(page - 1);

  return (
    <div className="new-stories-container">
      <h2 className="new-stories-title">New Stories</h2>
      {loading ? (
        <div className="spinner-container">
          <div className="spinner"></div>
        </div>
      ) : (
        <ul className="new-stories-list">
          {stories.map((story, index) => (
            <li key={index} className="new-stories-item">
              <a href={story.url} target="_blank">
                {story.title}
              </a>
            </li>
          ))}
        </ul>
      )}

      <div className="search-stories-pagination">
        <button
          onClick={prevPage}
          disabled={page === 1}
          className="new-stories-button"
        >
          Previous Page
        </button>
        <button onClick={nextPage} className="new-stories-button">
          Next Page
        </button>
      </div>
    </div>
  );
};

export default NewStories;

// Frontend/angular-app/src/app/new-stories/new-stories.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common'; // Import CommonModule
import { HackerNewsService } from '../hacker-news.service';

@Component({
  selector: 'app-new-stories',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './new-stories.component.html',
  styleUrls: ['./new-stories.component.css'],
})
export class NewStoriesComponent implements OnInit {
  stories: any[] = [];
  page: number = 1;
  limit: number = 20;
  loading: boolean = false;

  constructor(private hackerNewsService: HackerNewsService) {}

  ngOnInit(): void {
    this.fetchNewStories();
  }

  fetchNewStories(): void {
    this.hackerNewsService
      .getNewStories(
        this.page,
        this.limit,
        (loading) => (this.loading = loading)
      )
      .subscribe((data) => {
        this.stories = data;
      });
  }

  nextPage(): void {
    this.page++;
    this.fetchNewStories();
  }

  prevPage(): void {
    if (this.page > 1) {
      this.page--;
      this.fetchNewStories();
    }
  }
}

<!-- src/app/new-stories/new-stories.component.html -->
<div>
    <h2>New Stories</h2>
    <div *ngIf="loading" class="spinner-container">
        <div class="spinner"></div>
    </div>
    <ul *ngIf="!loading">
        <li *ngFor="let story of stories">
            <a [href]="story.url || '#'" target="_blank">{{ story.title }}</a>
        </li>
    </ul>
    <button (click)="prevPage()" [disabled]="loading || page === 1">Previous</button>
    <button (click)="nextPage()" [disabled]="loading">Next</button>
</div>
