// Frontend/hacker-news-react/src/components/SearchStories.tsx
import React, { useState } from "react";
import { searchStories } from "../services/HackerNewsService";
import "./SearchStories.css"; // Import the CSS file

interface Story {
  url: string | undefined;
  title: string;
}

const SearchStories: React.FC = () => {
  const [stories, setStories] = useState<Story[]>([]);
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(1);
  const [limit] = useState(20);
  const [loading, setLoading] = useState(false);

  const handleSearch = async () => {
    try {
      const data = await searchStories(query, page, limit, setLoading);
      setStories(data);
    } catch (error) {
      console.error(error.message);
    }
  };

  const nextPage = () => setPage(page + 1);
  const prevPage = () => page > 1 && setPage(page - 1);

  return (
    <div className="search-stories-container">
      <h1 className="search-stories-title">Search Stories</h1>
      <input
        type="text"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Search stories..."
        className="search-stories-input"
      />
      <button onClick={handleSearch} className="search-stories-button">
        Search
      </button>
      {loading ? (
        <div className="spinner-container">
          <div className="spinner"></div>
        </div>
      ) : (
        <ul className="search-stories-list">
          {stories.map((story, index) => (
            <li key={index} className="new-stories-item">
              <a href={story.url} target="_blank">
                {story.title}
              </a>
            </li>
          ))}
        </ul>
      )}
      <div className="search-stories-pagination">
        <button
          onClick={prevPage}
          disabled={page === 1}
          className="search-stories-pagination-button"
        >
          Previous Page
        </button>
        <button onClick={nextPage} className="search-stories-pagination-button">
          Next Page
        </button>
      </div>
    </div>
  );
};

export default SearchStories;

// Frontend/angular-app/src/app/search-stories/search-stories.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common'; // Import CommonModule
import { FormsModule } from '@angular/forms'; // Import FormsModule
import { HackerNewsService } from '../hacker-news.service';

@Component({
  selector: 'app-search-stories',
  standalone: true,
  imports: [CommonModule, FormsModule], // Include FormsModule here
  templateUrl: './search-stories.component.html',
  styleUrls: ['./search-stories.component.css'],
})
export class SearchStoriesComponent {
  stories: any[] = [];
  query: string = '';
  page: number = 1;
  limit: number = 20;
  loading: boolean = false;

  constructor(private hackerNewsService: HackerNewsService) {}

  searchStories(): void {
    this.hackerNewsService
      .searchStories(
        this.query,
        this.page,
        this.limit,
        (loading) => (this.loading = loading)
      )
      .subscribe((data) => {
        this.stories = data;
      });
  }

  nextPage(): void {
    this.page++;
    this.searchStories();
  }

  prevPage(): void {
    if (this.page > 1) {
      this.page--;
      this.searchStories();
    }
  }
}

<!-- src/app/search-stories/search-stories.component.html -->
<div>
    <h2>Search Stories</h2>
    <input type="text" [(ngModel)]="query" (input)="searchStories()" placeholder="Search stories...">

    <div *ngIf="loading" class="spinner-container">
        <div class="spinner"></div>
    </div>
    <ul *ngIf="!loading">
        <li *ngFor="let story of stories">
            <a [href]="story.url || '#'" target="_blank">{{ story.title }}</a>
        </li>
    </ul>
    <button (click)="prevPage()">Previous</button>
    <button (click)="nextPage()">Next</button>
</div>
